// <auto-generated />
namespace VisionWorkOrderApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddInspectionResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInspectionResult));
        
        string IMigrationMetadata.Id
        {
            get { return "202602261457231_AddInspectionResult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
